name: push
on: [push, workflow_dispatch]

permissions: {}
jobs:
  trigger_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger build in Ammar64/SharingBuilds
      run: |
        VERSION_NUMBER=$(python3 app/get_version_number.py)
        git clone --depth=1 https://github.com/Ammar64/SharingBuilds
        cd SharingBuilds
        git tag ${VERSION_NUMBER}
        git config --global user.name "Github Actions"
        git push https://Ammar64:${{ secrets.API_TOKEN_GITHUB }}@github.com/Ammar64/SharingBuilds ${VERSION_NUMBER}
