name: push
on: [push, workflow_dispatch]

permissions: {}
jobs:
  trigger_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger build in Ammar64/SharingBuilds
      run: |
        BNUM=$(git rev-list --count master)
        git clone --depth=1 https://github.com/Ammar64/SharingBuilds
        cd SharingBuilds
        git tag ${BNUM}
        git config --global user.name "Github Actions"
        git push https://Ammar64:${{ secrets.API_TOKEN_GITHUB }}@github.com/Ammar64/SharingBuilds ${BNUM}
